apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: le7ryl892-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: le7ryl892-go 
  name: le7ryl892-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: le7ryl892-go 
